@startuml
class Cargo {
    int Id
    string Nome
    int Nivel
}

class Funcionario {
    int Id
    string Nome
    bool Ativo
    decimal Salario
    List<Funcionario> Listar()
    #List<Funcionario> Listar(bool somenteAtivos)
}

class Avaliacao {
    int Id
    Funcionario Avaliado
    Gerente Avaliador
    DateTime RealizadaEm
    int Nota
    string Comentario
}

class Gerente {
    Funcionario Contratar(Funcionario novoFuncionario)
    Funcionario Demitir(Funcionario funcionario)
    Funcionario AumentarSalario(Funcionario funcionario, decimal novoSalario)
    List<Funcionario> Listar()
}

Funcionario <|-- Gerente
Funcionario o-- Cargo
Funcionario "1" *-- "muitos" Avaliacao : é avalidado
note bottom on link : Esse tipo de relacionamento indica \nque Funcionario tem uma lista \ndo tipo Avaliacao

Gerente "1" *-- "muitos" Avaliacao : avalia

note top of Funcionario : Classe principal que representa\n os funcionários da empresa
note left of Funcionario::Id
    As propriedades são 
    representadas assim
end note
note left of Gerente::Contratar
    Os métodos são 
    representados assim
end note
@enduml
